=== ElsevierKnowledgeBasedSystems/KNOSYS-D-15-01003/xjaf2x-server/src/org/xjaf2x/server/config/xjaf2x-server.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://perun.pmf.uns.ac.rs/xjaf2x/xjaf2x-server"
	xmlns:tns="http://perun.pmf.uns.ac.rs/xjaf2x/xjaf2x-server" elementFormDefault="qualified">

	<element name="xjaf2x-server">
		<complexType>
			<sequence>
				<element name="relay" minOccurs="0" maxOccurs="1">
					<complexType>
						<attribute name="address" type="string" use="required" />
						<attribute name="site" type="string" use="required" />
					</complexType>
				</element>

				<element name="agents" minOccurs="0" maxOccurs="1">
					<complexType>
						<sequence>
							<element name="agent" minOccurs="0" maxOccurs="unbounded">
								<complexType>
									<attribute name="family" type="string" use="required" />
									<attribute name="stateful" type="string" use="optional" />
									<attribute name="jason" type="string" use="optional" />
								</complexType>
							</element>
						</sequence>
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
</schema>

=== ElsevierKnowledgeBasedSystems/KNOSYS-D-15-01003/xjaf2x-server/src/org/xjaf2x/server/config/xjaf2x-server.xml
<?xml version="1.0" encoding="UTF-8"?>
<xjaf2x-server xmlns="http://perun.pmf.uns.ac.rs/xjaf2x/xjaf2x-server" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://perun.pmf.uns.ac.rs/xjaf2x/xjaf2x-server xjaf2x-server.xsd ">
	<relay address="192.168.8.1" site="site1" />
	<agents>
		<agent family="org.xjaf2x.server.agents.ping.PingAgent" stateful="false" />
		<agent family="org.xjaf2x.server.agents.ping.PingLoadTest" stateful="false" />
		<agent family="org.xjaf2x.server.agents.aco.tsp.MapAgent" />
		<agent family="org.xjaf2x.server.agents.aco.tsp.StarterAgent" stateful="false" />
		<agent family="org.xjaf2x.server.agents.cnet.CNetManager" />
		<agent family="org.xjaf2x.server.agents.cnet.CNetStarter" />
		<agent family="org.xjaf2x.server.agents.cnet.CNetContractor" />
		<agent family="org.xjaf2x.server.agents.jason.HelloJason" jason="true" />
		<agent family="org.xjaf2x.server.agents.jason.FactJason" jason="true" />
	</agents>
</xjaf2x-server>
